version: "3"
services:
  traefik:
    image: "traefik:latest"
    command: >-
      --api=true --api.insecure=true --api.dashboard=true --providers.docker
    container_name: traefik
    hostname: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${CONFIG}/traefik/acme.json:/acme.json"
      - "${CONFIG}/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "${CONFIG}/traefik/.htpasswd:/etc/traefik/.htpasswd:ro"
    labels:
      traefik.enable: "true"
      traefik.http.services.monitor-service.loadbalancer.server.port: "8080"
      traefik.http.routers.monitor.rule: "Host(`monitor.${DOMAIN}`)"
      traefik.http.routers.monitor.tls.certresolver: "sample"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "1900:1900/udp"
    volumes:
      - "${CONFIG}/plex:/config"
      - "${DATA}/series:/media/series_2"
      - "${DATA}/movies:/media/movies_2"
      - "${DATA}/pictures:/media/pictures"
    environment:
      - PGID
      - PUID
      - TZ
      - VERSION=latest
    labels:
      traefik.enable: "true"
      traefik.port: "32400"
      traefik.http.services.plex-service.loadbalancer.server.port: "32400"
      traefik.http.routers.plex.rule: "Host(`plex.${DOMAIN}`)"
      traefik.http.routers.plex.tls.certresolver: "sample"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - "${CONFIG}/sabnzbd:/config"
      - "${DOWNLOADS}/complete:/downloads"
      - "${DOWNLOADS}/incomplete:/incomplete-downloads"
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.http.routers.sabnzbd.rule: "Host(`sabnzbd.${DOMAIN}`)"
      traefik.http.routers.sabnzbd.tls.certresolver: "sample"
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - TZ=Europe/London
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - sabnzbd
    volumes:
      - "${CONFIG}/sonarr:/config"
      - "${DATA}/series:/tv2"
      - "${DOWNLOADS}/complete:/downloads"
    links:
      - sabnzbd
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "8989"
      traefik.http.routers.sonarr.rule: "Host(`sonarr.${DOMAIN}`)"
      traefik.http.routers.sonarr.tls.certresolver: "sample"
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    links:
      - sabnzbd
    volumes:
      - "${CONFIG}/radarr:/config"
      - "${DOWNLOADS}/complete:/downloads"
      - "${DATA}/movies:/movies2"
    restart: unless-stopped
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    labels:
      traefik.enable: "true"
      traefik.port: "7878"
      traefik.http.services.radarr-service.loadbalancer.server.port: "7878"
      traefik.http.routers.radarr.rule: "Host(`radarr.${DOMAIN}`)"
      traefik.http.routers.radarr.tls.certresolver: "sample"
      com.centurylinklabs.watchtower.enable: "true"
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - "${CONFIG}/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.services.portainer-service.loadbalancer.server.port: "9000"
      traefik.http.routers.portainer.rule: "Host(`portainer.${DOMAIN}`)"
      traefik.http.routers.portainer.tls.certresolver: "sample"
      com.centurylinklabs.watchtower.enable: "true"
  netdata:
    container_name: netdata
    image: titpetric/netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    environment:
      - TZ=Europe/Zurich
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    volumes:
      - "${CONFIG}/netdata:/etc/netdata"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      traefik.enable: "true"
      traefik.http.services.netdata-service.loadbalancer.server.port: "19999"
      traefik.http.routers.netdata.rule: "Host(`netdata.${DOMAIN}`)"
      traefik.http.routers.netdata.tls.certresolver: "sample"
      com.centurylinklabs.watchtower.enable: "true"
  watchtower:
    image: v2tec/watchtower
    command: '--cleanup --label-enable --schedule="0 2 * * *"'
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: unless-stopped
    environment:
      - TZ=Europe/Zurich
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - EAP=1
    volumes:
      - "${CONFIG}/ombi:/config"
    labels:
      traefik.enable: "true"
      traefik.http.services.ombi-service.loadbalancer.server.port: "3579"
      traefik.http.routers.ombi.rule: "Host(`ombi.${DOMAIN}`)"
      traefik.http.routers.ombi.tls.certresolver: "sample"
      com.centurylinklabs.watchtower.enable: "true"
  jdownloader-2:
    image: jlesage/jdownloader-2
    volumes:
      - "${CONFIG}/jdownloader-2:/config:rw"
      - "/opt/downloads_2:/output:rw"
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "5800"
      traefik.frontend.rule: "Host:jdownloader.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
  organzir:
    image: lsiocommunity/organizr
    container_name: organizr
    volumes:
      - "${CONFIG}/organizr:/config"
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
  plexpy:
    image: "linuxserver/tautulli:latest"
    container_name: tautulli
    hostname: tautulli
    restart: unless-stopped
    volumes:
      - "${CONFIG}/plexpy:/config"
      - >-
        ${CONFIG}/plex/Library/Application Support/Plex Media
        Server/Logs:/logs:ro
    labels:
      traefik.enable: "true"
      traefik.http.services.tautulli-service.loadbalancer.server.port: "8181"
      traefik.http.routers.tautulli.rule: "Host(`tautulli.${DOMAIN}`)"
      traefik.http.routers.tautulli.tls.certresolver: "sample"
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      - PGID
      - PUID
      - TZ=Europe/Zurich
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    restart: unless-stopped
    volumes:
      - "${CONFIG}/duplicati:/config"
      - "/opt/backup:/backup"
      - "${CONFIG}:/source"
    labels:
      traefik.enable: "true"
      traefik.port: "8200"
      traefik.http.services.tautulli-service.loadbalancer.server.port: "8200"
      traefik.http.routers.duplicati.rule: "Host(`duplicati.${DOMAIN}`)"
      traefik.http.routers.duplicati.tls.certresolver: "sample"
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      - PGID
      - PUID
      - TZ
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    volumes:
      - ${CONFIG}/ddclient:/config
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  wpdb:
    image: mysql:5.7
    volumes:
      - "${CONFIG}/wpdb:/var/lib/mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQLROOTPW}"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "${WPUSERPW}"
  wordpress:
    depends_on:
      - wpdb
    image: wordpress:latest
    restart: unless-stopped
    volumes:
      - "${CONFIG}/wordpress/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini"
      - "${CONFIG}/wordpress/html:/var/www/html"
      - "${CONFIG}/wordpress/php.ini:/etc/php/7.0/apache2/php.ini"
    environment:
      WORDPRESS_DB_HOST: "wpdb:3306"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "${WPUSERPW}"
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:blog.${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
